1
alexistav/admin-panel-makeup pull request #1
Opened 2022-01-17 10:58 UTC by alexistav

2022-01-19 23:45 UTC, Muslik requested changes

2022-01-19 23:45 UTC, Muslik commented on index.html
> +<!DOCTYPE html>
Размеры не по макету. Блока TableBody вообще не видно

2022-01-19 23:45 UTC, Muslik commented on index.html
> +<!DOCTYPE html>
Классы названы не по БЭМ

2022-01-20 13:54 UTC, alexistav commented on index.html
> +<!DOCTYPE html>
исправлено

2022-01-21 17:32 UTC, Muslik requested changes

2022-01-21 17:32 UTC, Muslik commented on index.html
> +<html lang="en">
Размеры центрального блока не соответствуют макету

2022-01-21 17:32 UTC, Muslik commented on index.html
> +<html lang="en">
border должен быть шире

2022-01-21 17:32 UTC, Muslik commented on index.html
> +      <div class="table-wrapper">
wrapper просто лишнее слово. Просто table

2022-01-21 17:32 UTC, Muslik commented on index.html
> +        <div class="table-wrapper__table-header"></div>
table-wrapper__table-header (table, table)

Можно проще:
table__header. Меньше кода, проще читать

2022-01-21 17:32 UTC, Muslik commented on index.html
> +          <p></p>
Не нужно

2022-01-22 02:29 UTC, alexistav commented on index.html
> +          <p></p>
удалила

2022-01-22 02:29 UTC, alexistav commented on index.html
> +        <div class="table-wrapper__table-header"></div>
упростила

2022-01-22 02:29 UTC, alexistav commented on index.html
> +      <div class="table-wrapper">
принято

2022-01-22 02:29 UTC, alexistav commented on index.html
> +<html lang="en">
исправила

2022-01-24 14:49 UTC, Muslik requested changes
Работа не соответсвует макету. Таблица должна доходить до конца страницы

2022-01-25 17:12 UTC, Muslik requested changes
Размеры не по макету. Размер header, footer в таблице к примеру. Плюс на странице присутствует скролл которого быть не должно. У title есть line-height. У body нужно обнулить дефолтные браузеровские margin-ы

2022-01-29 16:33 UTC, Muslik requested changes
Верстка не совпадает с макетом.

2022-02-04 21:25 UTC, Muslik approved these changes
Хорошо

2022-02-05 06:00 UTC, merged